POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "restaurantId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "name": "John Doe",
  "email": "john@example.com",
  "street": "Main Street",
  "number": "42A",
  "postalCode": "1000",
  "city": "Brussels",
  "country": "Belgium",
  "orderLines": [
    { "dishId": "ffffffff-1111-2222-3333-444444444444", "quantity": 2, "priceAtCheckout": 12.50 },
    { "dishId": "ffffffff-aaaa-bbbb-cccc-dddddddddddd", "quantity": 1, "priceAtCheckout": 24.50 }
  ],
  "payment": {
    "paymentId": "99999999-1111-2222-3333-444444444444",
    "provider": "PAYPAL",
    "status": "PENDING"
  }
}

###
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "restaurantId": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "name": "Jane Doe",
  "email": "jane@example.com",
  "street": "Main Street",
  "number": "42A",
  "postalCode": "1000",
  "city": "Brussels",
  "country": "Belgium",
  "orderLines": [],
  "payment": {
    "paymentId": "99999999-1111-2222-3333-444444444444",
    "provider": "PAYPAL",
    "status": "PENDING"
  }
}
###
//http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/auth?client_id=backend-client&response_type=code&scope=openid&redirect_uri=http://localhost:3333/callback

POST http://localhost:8180/realms/keepdishesgoing/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=backend-client
    &client_secret=C1Ur8iF2SPSu3CtTx0tKsidAvmhRTiba
    &grant_type=authorization_code
    &scope=openid
    &redirect_uri=http://localhost:3333/callback
    &code=5ffb993b-36f2-493d-a4d8-7264e1247951.c3dbfe10-d9f4-4245-a7b0-1e916410b639.c3c0fda5-d051-439c-916b-f8ff9c2fb328
> {%
    client.global.set("access_token", response.body.access_token);
%}

### accept an order
POST http://localhost:8080/api/orders/9a26749a-e66f-4824-ba74-4194025b2dc1/accept
Authorization: Bearer {{access_token}}
Content-Type: application/json

### reject with reason
POST http://localhost:8080/api/orders/56130e1e-1537-445c-9469-891c56a497bd/reject
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "reason": "Restaurant is closed"
}
### mark as ready for pick up( only for accepted orders)
POST http://localhost:8080/api/orders/9a26749a-e66f-4824-ba74-4194025b2dc1/ready
Authorization: Bearer {{access_token}}
Content-Type: application/json

