### 1. Register Owner
POST http://localhost:8080/owners/signup
Content-Type: application/json

{
  "email": "anir@example.com",
  "password": "secret123",
  "name": "anir"
}

###

### 2. Sign In (to verify works)
POST http://localhost:8080/owners/signin
Content-Type: application/json

{
  "email": "anir@example.com",
  "password": "secret123"
}

###

### 3. Create Restaurant for that owner
POST http://localhost:8080/restaurants
Content-Type: application/json

{
  "ownerId": "d853346e-a7ff-4c94-aad1-250c60003ca2",
  "restaurantName": "Ice cream",
  "streetName": "Grand Place",
  "streetNumber": "423A",
  "postalCode": "1000",
  "city": "Antwerpen",
  "country": "Belgium",
  "contactEmail": "georgeburger@restaurant.be",
  "pictureUrl": "https://skip-strapi-prod.s3.us-west-2.amazonaws.com/burgers_1_9e9eaa22f6.jpg?w=3840&q=100",
  "typeOfCuisine": "American",
  "defaultPreparationTime": 15,
  "openingHours": {
    "monday": "12:00-23:00",
    "tuesday": "12:00-23:00",
    "saturday": "16:00-23:00"
  }
}


###